### ISSUE TITLE
调用的问题

### ISSUE THREAD

**Issue by wilddylan** [suguangwen/vue-rolling#4]
``` html
<div v-scroll="loadMore()" scroll-foot="49" scroll-top="49" scroll-up="refresh()">
      <div class="recommend-content-list">
        <div class="rec-refresh">
          <img src="../../static/imgs/spinner.png"/>
        </div>
        <div class="rec-header">
        </div>
        <div class="rec-item" v-for="item in items" track-by="$index">
          {{ item }}
          <br>
        </div>
      </div>
      <div class="rec-loadmore">
          <img src="../../static/imgs/spinner.png"/>
      </div>
      <div class="fix-tab"></div>
    </div>
```

``` css
.recommend-content-list {
    width: 100%;
  }
  .fix-tab {
    width: 100%;
    height: 49px;
  }
  .rec-loadmore {
    height: 49px;
    width: 100%;
    text-align: center;
  }
  .rec-refresh {
    height: 49px;
    width: 100%;
    text-align: center;
  }
  .rec-loadmore img, .rec-refresh img {
    width: 20px;
    height: 20px;
    margin-top: 15px;
    -webkit-animation: gogogo .5s infinite linear;
  }
```

``` javaScript
var height = $(window).height()
var self = this
var navigation = $('drnavigation-bar')
var tabBar = $('drtabbar')
if ( navigation ) {
    height -= 64;
}
if ( tabBar ) {
    height -= 49;
} 
$('.recommend-content-list').height(height);
```

触发多次refresh。
在触发下拉刷新后, 刷新的控件一直存在, 导致在这种状态下继续下拉还会不停的调用refresh方法。 
小白, 请指教。
